energymanager/start_site/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from energymanager.start_site import views

urlpatterns = patterns(
    'legacy.website.views',
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^apps/$', views.AppsView.as_view(), name='apps'),
)

gridagentserver/legacy/website/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'legacy.website.views',
    url(r'^$',
        'find_home',
        name='website-home'),
    url(r'^login/$', 'login', name='website-login'),
    url(r'^logout/$', 'logout', name='website-logout'),
    url(r'^legacy_task_status/$', 'task_status', name='website-task_status'),
    url(r'^cancel_task/$', 'cancel_task', name='website-cancel_task'),
    url(r'^json_task_result/$', 'json_task_result',
        name='website-json_task_result'),
)

gridplatform/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.contrib import admin
import django.contrib.auth.models
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
import djcelery.models

from gridplatform.utils.urls import restricted_url


js_info_dict = {
    'packages': (
        'legacy.website',
        'legacy.manage_devices',
        'legacy.manage_customers',
    ),
}


urlpatterns = patterns(
    '',
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jserror/', include('gridplatform.jserror.urls')),
    url(r'^task_status/$',
        'gridplatform.utils.views.task_status',
        name='task_status'),
    url(r'^manage/customers/', include('legacy.manage_customers.urls')),
    url(r'^manage/agents/', include('legacy.setup_agents.urls')),
    url(r'^locations/', include('legacy.manage_locations.urls')),
    url(r'^groups/', include('legacy.manage_collections.urls')),
    url(r'^devices/', include('legacy.manage_devices.urls')),
    url(r'^measurementpoints/',
        include(
            'legacy.manage_measurementpoints.urls',
            namespace='manage_measurementpoints')),
    url(r'^overview/details/',
        include('legacy.display_measurementpoints.urls')),
    url(r'^overview/indexes/',
        include('legacy.display_indexes.urls')),
    url(r'^projects/', include('legacy.display_projects.urls')),
    url(r'^users/', include('legacy.manage_users.urls')),
    url(r'^widgets/', include('legacy.display_widgets.urls')),
    url(r'^userprofile/', include('legacy.edit_userprofile.urls')),
    url(r'^rules/', include('legacy.manage_rules.urls')),
    url(r'^indexes/', include('legacy.manage_indexes.urls')),
    url(r'^reports/', include('legacy.manage_reports.urls')),
    url(r'', include('legacy.website.urls')),
    url('^energy_use_reports/',
        include('legacy.energy_use_reports.urls')),
    url('^enpi_reports/',
        include('legacy.enpi_reports.urls')),
    url(r'^report_generators/', include('gridplatform.reports.urls')),
    url(r'^project_generators/', include('legacy.projects.urls')),
    url(r'^start/',
        include('energymanager.start_site.urls', namespace='start_site')),
    url(r'^user/', include('gridplatform.users.urls', namespace='users')),
    # Provider site
    restricted_url(
        r'^admin/',
        include('energymanager.provider_site.urls',
                namespace='provider_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    restricted_url(
        r'^configuration/',
        include('energymanager.configuration_site.urls',
                namespace='configuration_site'),
        permission='users.access_provider_site',
        requires_provider=True),
    # LED Light site
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.urls',
                namespace='led_light_site'),
        permission='users.access_led_light_site'),

    # HACK to restrict project urls
    # TODO: Figure out why restricted_url doesn't work in app url files
    restricted_url(
        r'^led_light/',
        include('energymanager.led_light_site.restricted_urls',
                namespace='led_light_site_projects'),
        permission='users.access_led_light_site_projects'),

    # Access price_relay site
    restricted_url(
        r'^price_relay/',
        include('energymanager.price_relay_site.urls',
                namespace='price_relay_site'),
        permission='users.access_price_relay_site'),

    # Project site
    restricted_url(
        r'^escolite/',
        include('energymanager.project_site.urls',
                namespace='project_site'),
        permission='users.access_project_site'),


    # REST API
    url(r'^api/current/',
        RedirectView.as_view(url=reverse_lazy('api:api-root')),
        name='api-current-version'),
    url(r'^api/v3/', include('gridplatform.api', namespace='api')),
)


admin.autodiscover()

admin.site.unregister(django.contrib.auth.models.User)

admin.site.unregister(djcelery.models.TaskState)
admin.site.unregister(djcelery.models.WorkerState)
admin.site.unregister(djcelery.models.IntervalSchedule)
admin.site.unregister(djcelery.models.CrontabSchedule)
admin.site.unregister(djcelery.models.PeriodicTask)


urlpatterns += patterns(
    '',
    restricted_url(
        r'^sysadmin/',
        include(admin.site.urls),
        requires_is_staff=True),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^qunit/', include('django_qunit.urls')),
    )

legacy/website/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'legacy.website.views',
    url(r'^$',
        'find_home',
        name='website-home'),
    url(r'^login/$', 'login', name='website-login'),
    url(r'^logout/$', 'logout', name='website-logout'),
    url(r'^legacy_task_status/$', 'task_status', name='website-task_status'),
    url(r'^cancel_task/$', 'cancel_task', name='website-cancel_task'),
    url(r'^json_task_result/$', 'json_task_result',
        name='website-json_task_result'),
)

wifiagent/wifiagent/urls.py
from django.conf.urls import url
#from django.contrib import admin

from wifiagent.relay import views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^reciever/$', views.reciever),
]

gridagentserver/legacy/website/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db.models.signals import post_save

from gridplatform.users.models import User
from legacy.legacy_utils.models import UserProfile


def create_user_profile(sender, instance, created, raw=False, **kwargs):
    if created and not raw:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

legacy/website/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db.models.signals import post_save

from gridplatform.users.models import User
from legacy.legacy_utils.models import UserProfile


def create_user_profile(sender, instance, created, raw=False, **kwargs):
    if created and not raw:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

gridagentserver/legacy/website/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import urlparse

from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.shortcuts import redirect
from django.utils.encoding import python_2_unicode_compatible
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.views import logout_then_login
from django.contrib.sites.models import get_current_site

from celery.result import AsyncResult
import celery.task.control

from gridplatform.users.decorators import auth_or_error
from gridplatform.utils.views import render_to, json_response
from gridplatform.trackuser import get_user
from gridplatform.trackuser import get_customer


@sensitive_post_parameters()
@csrf_protect
@never_cache
@render_to('website/login.html')
def login(request):
    """
    Displays the login form and handles the login action.
    """
    # based on django.contrib.auth.views.login --- "simplified" by removing
    # parameters, call to load encryption keys added.
    redirect_to = request.REQUEST.get(REDIRECT_FIELD_NAME, '')

    # HACK: ONLY FOR USE ON GREENTECH SERVERS
    # if request.method == "POST" or "username" in request.GET:
    #     if 'username' in request.GET:
    #         form = AuthenticationForm(data=request.GET)
    #     else:
    #         form = AuthenticationForm(data=request.POST)

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            netloc = urlparse.urlparse(redirect_to)[1]

            # Use default setting if redirect_to is empty
            if not redirect_to:
                redirect_to = settings.LOGIN_REDIRECT_URL

            # Heavier security check -- don't allow redirection to a different
            # host.
            elif netloc and netloc != request.get_host():
                redirect_to = settings.LOGIN_REDIRECT_URL

            # Okay, security checks complete. Log the user in.
            auth_login(request, form.get_user())

            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()

            return HttpResponseRedirect(redirect_to)
    else:
        form = AuthenticationForm(request)

    request.session.set_test_cookie()

    current_site = get_current_site(request)

    return {
        'form': form,
        'REDIRECT_FIELD_NAME': redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }


@never_cache
def logout(request):
    return logout_then_login(request)


def find_home(request):
    if get_user().is_staff:
        return redirect('manage_customers-list')
    else:
        return redirect('display_widgets-dashboard')


@python_2_unicode_compatible
class CeleryError(Exception):
    """
    Wrapper for exceptions from Celery --- Celery provides an Exception object
    and a string representation of a traceback.
    """
    def __init__(self, wrapped, traceback):
        self.wrapped = wrapped
        self.traceback = traceback

    def __str__(self):
        return '{}\n{}'.format(self.wrapped, self.traceback)


@auth_or_error
@json_response
@require_POST
def task_status(request):
    """
    Given a celery task ID the status of that task is returned.

    If the task has failed, this raises an exception to trigger the normal
    Django error reporting.
    """
    task_id = request.POST['task_id']
    async = AsyncResult(task_id)

    # We have experienced async.failed() being false while async.result
    # contained an AssertionError instance.  Hence the isinstance check.
    if async.failed() or isinstance(async.result, Exception):
        # NOTE: The available "traceback" is a string, not a traceback-object,
        # hence "re-raising" with that as traceback context will not work

        if async.status == 'REVOKED':
            return {
                'task_id': async.id,
                'status': async.status
            }
        else:
            raise CeleryError(async.result, async.traceback)

    if async.status == "PROGRESS":
        return {
            'task_id': async.id,
            'status': async.status,
            'result': async.result,
        }
    else:
        return {
            'task_id': async.id,
            'status': async.status,
        }


@auth_or_error
@json_response
@require_POST
def cancel_task(request):
    """
    Kills a task with the given ID, if the logged in user
    is the same user that started the task
    """
    task_id = request.POST['task_id']
    async = AsyncResult(task_id)
    success = False
    if async and isinstance(async.result, dict) and \
            get_user().id == async.result.get('task_user_id', None):
        # NOTE: The Celery documentation recommends against using termitate
        # programmatically --- the worker in question is terminated, though it
        # may have started processing a different task when the termination
        # signal is delivered.  As we have enabled CELERY_ACKS_LATE, the harm
        # in that particular case is limited --- any next/different task being
        # processed by the terminated worker will be retried by another worker,
        # rather than being lost (as it would have been without
        # CELERY_ACKS_LATE)...
        celery.task.control.revoke(task_id, terminate=True)
        success = True
    return {
        'success': success
    }


@auth_or_error
@json_response
@require_POST
def json_task_result(request):
    """
    Given a celery task ID of a completed task, the result is returned. The
    result from the task must be serializable to JSON.
    """
    task_id = request.POST['task_id']
    async = AsyncResult(task_id)
    assert async.successful(), async.traceback

    # HACK: Production units cannot be displayed in tasks because they are
    # encrypted.  So we replace them here with their decrypted counter parts.
    def replace_production_unit(s, l):
        return s.replace(
            'production_%s' % l, getattr(
                get_customer(),
                'production_%s_unit_plain' % l))

    for letter in ['a', 'b', 'c', 'd', 'e']:
        try:
            async.result['options']['yaxis']['title'] = \
                replace_production_unit(async.result[
                    'options']['yaxis']['title'], letter)
        except KeyError:
            pass
        try:
            async.result['options']['xaxis']['title'] = \
                replace_production_unit(async.result[
                    'options']['xaxis']['title'], letter)
        except KeyError:
            pass
    return async.result

legacy/website/templates/admin_menu.html
{% spaceless %}
{% load static from staticfiles %}
{% load url from future %}
{% load i18n %}

<div class="menu-item customers">
  <a href="{% url 'manage_customers-list' %}">
    <div class="icon"></div>
    <span>{% trans "Customers" %}</span>
  </a>
</div>

<div class="menu-item devices">
  <a href="{% url 'setup_agents-list' %}">
    <div class="icon"></div>
    <span>{% trans "Agents" %}</span>
  </a>
</div>

{% if user.is_admin and request.customer %}
{% include "admin_superuser_menu_points.html" %}
{% endif %}

<div class="menu-right-border"></div>
{% endspaceless %}

legacy/website/templates/admin_settings_menu.html
{% spaceless %}
{% load static from staticfiles %}
{% load url from future %}
{% load i18n %}

<div class="menu-item userprofile">
  <a href="{% url 'edit_userprofile' pk=user.id %}">
    <div class="icon"></div>
    <span>{% trans "User Profile" %}</span>
  </a>
</div>

<div class="menu-right-border"></div>
{% endspaceless %}

legacy/website/templates/base.html
{% spaceless %}
{% load static from staticfiles %}
{% load url from future %}
{% load i18n %}
{% load dropdown %}
{% load version %}
{% load customer %}
{% load gminfo %}
{% load compress %}


<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>SC Portal - {% block title %}{% endblock %}</title>
    {% block base_css %}
    {% compress css %}
    <link rel="stylesheet" href="{% static '960gs/min/reset.css' %}">
    <link rel="stylesheet" href="{% static '960gs/min/text.css' %}">
    <link rel="stylesheet" href="{% static '960gs/min/960_24_col.css' %}">
    <link rel="stylesheet" href="{% static 'jquery/smoothness/jquery-ui-1.9.2.custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-dropdown/jquery.dropdown.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-timepicker/jquery-ui-timepicker-addon.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'slickswitch/css/slickswitch.css' %}">
    <link rel="stylesheet" href="{% static 'custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'fancybox/jquery.fancybox-1.3.4.css' %}">
    {% endcompress %}

    {% if request.get_host == "portal.smartflex.dk" %}
      <link rel="stylesheet" href="{% static 'style-smartflex.css' %}" />
    {% elif request.get_host == "endesa.grid-manager.com" %}
      <link rel="stylesheet" href="{% static 'style-endesa.css' %}" />
    {% else %}
      <link rel="stylesheet" href="{% static 'style.css' %}" />
    {% endif %}
    <!--[if IE]>
    <style type="text/css">
      .btn {
        margin-left: 2px;
        margin-top: 0px;
      }
      .loginform {
        margin: 5px;
      }
    </style>
    <![endif]-->

    {# Hack to rotate text in ie 8 #}
    <!--[if lt IE 9]>
    <style type="text/css">
      .rotate {
        filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);

        top: 1px!important;
        left: 2px!important;
      }
    </style>
    <![endif]-->
    {% endblock base_css %}
    {% block page_css %}{% endblock page_css %}
    {% block base_js %}
    {% include "jserror/include.html" %}
    {# translations just before our code... #}
    <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
    {% compress js %}
    <script type="text/javascript" src="{% static 'jquery/jquery-1.8.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery/jquery-ui-1.9.2.custom.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'chosen/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'custom-scrollbar-plugin/minified/jquery.mousewheel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'custom-scrollbar-plugin/minified/jquery.mCustomScrollbar.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.labelify.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.scrollTo-1.4.2.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.ui.touch-punch.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery.showpassword.js' %}"></script>
    <script type="text/javascript" src="{% static 'noty/jquery.noty.js' %}"></script>
    <script type="text/javascript" src="{% static 'noty/layouts/topCenter.js' %}"></script>
    <script type="text/javascript" src="{% static 'noty/themes/gridmanager.js' %}"></script>
    <script type="text/javascript" src="{% static 'flotr2.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-dropdown/jquery.dropdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'jstree/jquery.jstree.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-timepicker/jquery-ui-sliderAccess.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-timepicker/jquery-ui-timepicker-addon.js' %}"></script>
    <script type="text/javascript" src="{% static 'jsgauge/gauge.js' %}"></script>
    <script type="text/javascript" src="{% static 'jsgauge/jquery.gauge.js' %}"></script>
    <script type="text/javascript" src="{% static 'slickswitch/js/jquery.slickswitch.js' %}"></script>
    <script type="text/javascript" src="{% static 'fancybox/jquery.fancybox-1.3.4.pack.js' %}"></script>
    <script type="text/javascript" src="{% static 'website.js' %}"></script>
    {% endcompress %}
    <script type="text/javascript">
/*jslint browser: true, devel: true */
/*jslint todo: true */
/*global $, jQuery, gettext, pgettext, get_format, noty, gridportal */
/*jslint sub: true */ {# make jslint not complain about regional['all'] #}

jQuery(function () {
    'use strict';
    gridportal.website.slideSettings();
});
$.datepicker.regional['all'] = {
    closeText: '{% trans "Close" %}',
    prevText: '{% trans "Previous" %}',
    nextText: '{% trans "Next" %}',
    currentText: '{% trans "Now" %}',
    monthNames: ['{% trans "January" %}', '{% trans "February" %}', '{% trans "March" %}', '{% trans "April" %}', '{% trans "May" %}', '{% trans "June" %}', '{% trans "July" %}', '{% trans "August" %}', '{% trans "September" %}', '{% trans "October" %}', '{% trans "November" %}', '{% trans "December" %}'],
    monthNamesShort: ['{% trans "Jan" %}', '{% trans "Feb" %}', '{% trans "Mar" %}', '{% trans "Apr" %}', '{% trans "May" %}', '{% trans "June" %}', '{% trans "July" %}', '{% trans "Aug" %}', '{% trans "Sept" %}', '{% trans "Oct" %}', '{% trans "Nov" %}', '{% trans "Dec" %}'],
    dayNames: ['{% trans "Sunday" %}', '{% trans "Monday" %}', '{% trans "Tuesday" %}', '{% trans "Wednesday" %}', '{% trans "Thursday" %}', '{% trans "Friday" %}', '{% trans "Saturday" %}'],
    dayNamesShort: ['{% trans "Sun" %}', '{% trans "Mon" %}', '{% trans "Tue" %}', '{% trans "Wed" %}', '{% trans "Thu" %}', '{% trans "Fri" %}', '{% trans "Sat" %}'],
    dayNamesMin: ['{% trans "Su" %}', '{% trans "Mo" %}', '{% trans "Tu" %}', '{% trans "We" %}', '{% trans "Th" %}', '{% trans "Fr" %}', '{% trans "Sa" %}'],
    weekHeader: '{% trans "Wk" context "abbreviation for week" %}',
    dateFormat: 'yy-mm-dd',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: ''
};
$.datepicker.setDefaults($.datepicker.regional['all']);
$.timepicker.regional['all'] = {
    timeOnlyTitle: '{% trans "Choose a time" %}',
    timeText: '{% trans "Time" %}',
    hourText: '{% trans "Hour" %}',
    minuteText: '{% trans "Minute" %}',
    secondText: '{% trans "Second" %}',
    millisecText: '{% trans "Millisecond" %}',
    timezoneText: '{% trans "Timezone" %}',
    currentText: '{% trans "Now" %}',
    closeText: '{% trans "Close" %}',
    timeFormat: 'HH:mm',
    amNames: ['AM', 'A'],
    pmNames: ['PM', 'P'],
    isRTL: false
};
$.timepicker.setDefaults($.timepicker.regional['all']);
    </script>
    {% endblock base_js %}
    {% block extra_js %}{% endblock extra_js %}
    {% block page_js %}{% endblock page_js %}
  </head>
  <body id="{% block page_id %}{% endblock %}">
    <div id="header">
      <div class="container_24">
        <div class="grid_8">
          <a href="{% url 'display_widgets-dashboard' %}">
            <h1>
              SC Portal
            </h1>
          </a>
          {% if app_selection|length > 1 %}
          <span class="app_switcher">&nbsp;&nbsp;
            <a href="{% url 'start_site:apps' %}">{% trans 'Apps' %}</a>
          </span>
          {% endif %}
        </div>
        <div class="grid_12 truncate-text">
          {% if user.is_admin and request.customer %}
          <a href="{% url 'manage_customers-as_admin' %}">{% trans 'Go back to admin mode' %}</a>
          <span>&nbsp;-&nbsp;</span>
          <span>{% trans 'Acting for customer:' %} {{ request.customer.name_plain }}.</span>
          {% elif user.is_authenticated and not user.is_admin %}
            <span class=" right">{% username %} - {% customer_name %}</span>
          {% else %}
            <span>&nbsp;</span>
          {% endif %}
        </div>
        <div class="grid_4">
          <div class="right">
            <span class="language">
              <form name="setLangDanish" action="/i18n/setlang/" method="POST">{% csrf_token %}
                  <input name="next" type="hidden" value="/" />
                  <input type="hidden" name="language" value="da" />
                  <span class="flag"><a href="#" onclick="document.setLangDanish.submit();return false;"><img src="{% static 'images/danish.png' %}" /></a></span>
              </form>

              <form name="setLangSpanish" action="/i18n/setlang/" method="POST">{% csrf_token %}
                  <input name="next" type="hidden" value="/" />
                  <input type="hidden" name="language" value="es" />
                  <span class="flag"><a href="#" onclick="document.setLangSpanish.submit();return false;"><img src="{% static 'images/spanish.png' %}" /></a></span>
              </form>

              <form name="setLangEnglish" action="/i18n/setlang/" method="POST">{% csrf_token %}
                  <input name="next" type="hidden" value="/" />
                  <input type="hidden" name="language" value="en" />
                  <span class="flag"><a href="#" onclick="document.setLangEnglish.submit();return false;"><img src="{% static 'images/english.png' %}" /></a></span>
              </form>
            </span>
            {% if user.is_authenticated %}
              <span class="logout"><a href="{% url 'website-logout' %}">{% trans "Logout" %}<img src="{% static 'images/logout.png' %}" /> </a></span>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div id="menu">
      <div class="container_24">
        <div class="grid_24 wrapper">
          {% if user.is_admin %}
            {% include "admin_menu.html" %}
          {% elif user.is_customer_superuser %}
            {% include "customer_superuser_menu.html" %}
          {% elif user.is_authenticated %}
            {% include "customer_user_menu.html" %}
          {% endif %}
        </div>
      </div>
    </div>
    {% comment %}
      reason for the rather deep nesting of tags:
      settings-menu for overall placement of menu with css;
      slide has relative position within (open/closed...) and full width
      container_24/grid_24 for the content width
    {% endcomment %}
    <div id="settings-menu">
      <div class="slide">
        <div class="container_24">
          <div class="grid_24">
            <div class="left">
              {% if user.is_admin and not request.customer %}
                {% include "admin_settings_menu.html" %}
              {% elif user.is_admin or user.is_customer_superuser %}
                {% include "customer_superuser_settings_menu.html" %}
              {% elif user.is_authenticated %}
                {% include "customer_user_settings_menu.html" %}
              {% endif %}
            </div>
            <div class="right">
              {% if user.is_authenticated %}
                <div class="settings-btn-background">
                  <div class="settings-btn">{% trans "Settings" %}</div>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="content">
      <div id="content-header" class="container_24">
        <div class="grid_24">
          <h1>{% block content_heading %}{% endblock %}</h1>
          {% block tabs %}{% endblock tabs %}
        </div>
      </div>
      <div id="content-main" class="content container_24">
        {% block content %}
        <div class="grid_24">{% block left_content %}{% endblock %}</div>
        {% endblock %}
        {% block in_page_menu %}{% endblock %}
      </div>
    </div>
    <div id="footer">
      <div class="container_24">
        <div class="grid_24">
	  <div class="left">
	    SC-Technology Aps <br />
      Søbyvej 18B <br />
      7840 Højslev
	  </div>
	  <div class="right">
	    {% gridplatform_version %}
	  </div>
        </div>
      </div>
    </div>
    {% block end %}{% endblock end %}
    {% block after_content %}
    {# Workaround; for popups/other managed by JS-libraries that fail to manage positioning inside the grid.  See list_page.html for example use... #}
    {% dropdown_bodies %}
    {% endblock %}
  </body>
</html>
{% endspaceless %}

legacy/website/templates/customer_superuser_menu.html
{% spaceless %}
{% load static from staticfiles %}
{% load url from future %}
{% load i18n %}

<div class="menu-item dashboard">
  <a href="{% url 'display_widgets-dashboard' %}">
    <div class="icon"></div>
    <span>{% trans "Dashboard" %}</span>
  </a>
</div>

{% include "admin_superuser_menu_points.html" %}

<div class="menu-right-border"></div>
{% endspaceless %}